const List<Map<String, String>> POPULAR_LOCATIONS = [
  {"city": "Aligarh", "country": "India"},
  {"city": "Mumbai", "country": "India"},
  {"city": "Delhi", "country": "India"},
  {"city": "Bangalore", "country": "India"},
  {"city": "Hyderabad", "country": "India"},
  {"city": "Chennai", "country": "India"},
  {"city": "Kolkata", "country": "India"},
  {"city": "Pune", "country": "India"},
  {"city": "Ahmedabad", "country": "India"},
  {"city": "Jaipur", "country": "India"},
  {"city": "Lucknow", "country": "India"},
  {"city": "Mecca", "country": "Saudi Arabia"},
  {"city": "Medina", "country": "Saudi Arabia"},
  {"city": "Riyadh", "country": "Saudi Arabia"},
  {"city": "Dubai", "country": "United Arab Emirates"},
  {"city": "Abu Dhabi", "country": "United Arab Emirates"},
  {"city": "Cairo", "country": "Egypt"},
  {"city": "Istanbul", "country": "Turkey"},
  {"city": "London", "country": "United Kingdom"},
  {"city": "New York", "country": "USA"},
  {"city": "Los Angeles", "country": "USA"},
  {"city": "Toronto", "country": "Canada"},
  {"city": "Paris", "country": "France"},
  {"city": "Singapore", "country": "Singapore"},
  {"city": "Kuala Lumpur", "country": "Malaysia"},
  {"city": "Jakarta", "country": "Indonesia"},
  {"city": "Tokyo", "country": "Japan"},
  {"city": "Sydney", "country": "Australia"},
  {"city": "Islamabad", "country": "Pakistan"},
  {"city": "Dhaka", "country": "Bangladesh"},
  {"city": "Lagos", "country": "Nigeria"},
  {"city": "Johannesburg", "country": "South Africa"},
  {"city": "Karachi", "country": "Pakistan"},
  {"city": "Lahore", "country": "Pakistan"},
  {"city": "Srinagar", "country": "India"},
  {"city": "Patna", "country": "India"},
  {"city": "Bhopal", "country": "India"},
];
