name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest # Standard is fine now
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Clean and Get Dependencies
        run: |
          flutter clean
          flutter pub get
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          pod install --repo-update
          cd ..

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Create IPA
        working-directory: build/ios/iphoneos
        run: |
          mkdir -p Payload
          mv Runner.app Payload/
          zip -qq -r -9 FlutterIpaExport.ipa Payload

      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0.${{ github.run_number }}
          overwrite: true